# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: deno fresh
    init: curl -fsSL https://deno.land/install.sh | sh
    command: |
      export DENO_INSTALL="/home/gitpod/.deno"
      export PATH="$DENO_INSTALL/bin:$PATH"
      cd silver-pancake
      ls

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: silver-pancake
    description: show the app
    port: 8000
    onOpen: open-browser
    visibility: public
