# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: echo 'deno fresh'
    init: curl -fsSL https://deno.land/install.sh | sh
    command: |
      cd silver-pancake
      ls

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: silver-pancake
    description: show the app
    port: 8910
    onOpen: open-preview
    visibility: public
